spring:
    datasource:
        url: jdbc:mysql://localhost:3306/msg?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123123123
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            initial-size: 5 #连接池初始化大小
            min-idle: 10 #最小空闲连接数
            max-active: 20 #最大连接数
            web-stat-filter:
                exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,*.html" #不统计这些请求数据
            stat-view-servlet: #访问监控网页的登录用户名和密码
                login-username: admin
                login-password: admin
                enabled: true
                url-pattern: /druid/*
                reset-enable: true
    application:
        name: 留言板程序
mybatis:
    mapper-locations: classpath:/mapper/*.xml

swagger:
    base-path: /**
    base-package: 'com.xrluo'
    title: 'spring-boot-swagger-demo'
    description: '基于Swagger构建的SpringBoot RESTApi 文档'
    version: '1.0'
    contact:
        name: '氷落'
        url: 'http://blog.xrluo.com'
        email: 'admin@xrluo.com'